const projects = [
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "1418",
    "resourceName": "Renewable Energy Project by LNB Group",
    "proponent": "Renewable Energy Project by LNB Group",
    "operator": null,
    "designee": null,
    "protocolCategories": "Renewable",
    "resourceStatus": "Registered",
    "country": "Colombia",
    "estAnnualEmissionReductions": 29404,
    "region": "Latin America",
    "version": "VCS Version 3",
    "protocols": "AR-ACM0003",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-06-03"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "1686",
    "resourceName": "Cumare carbon project",
    "proponent": "Reforestadora Cumare S.A.S.",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under development",
    "country": "Colombia",
    "estAnnualEmissionReductions": 29404,
    "region": "Latin America",
    "version": "VCS Version 3",
    "protocols": "AR-ACM0003",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-06-03"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2532",
    "resourceName": "Cumare carbon project",
    "proponent": "Reforestadora Cumare S.A.S.",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under development",
    "country": "Colombia",
    "estAnnualEmissionReductions": 29404,
    "region": "Latin America",
    "version": "VCS Version 3",
    "protocols": "AR-ACM0003",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-06-03"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2518",
    "resourceName": "Carbon sequestration in mangroves of the south – central coastal zone of the state of Sinaloa, México",
    "proponent": "ALLCOT AG",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under development",
    "country": "Mexico",
    "estAnnualEmissionReductions": 3123836,
    "region": "Latin America",
    "version": "VCS Version 3",
    "protocols": "VM0007",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-05-12"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2511",
    "resourceName": "Joburg Landfill Gas to Energy Project.",
    "proponent": "Converted from other GHG program",
    "operator": null,
    "designee": null,
    "protocolCategories": "Waste handling and disposal",
    "resourceStatus": "Credits Transferred from Approved GHG Program",
    "country": "South Africa",
    "estAnnualEmissionReductions": 480155,
    "region": "Africa",
    "version": "VCS Version 3",
    "protocols": "ACM0001",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-04-28"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2509",
    "resourceName": "A-Gas SA ODS Project",
    "proponent": "A-Gas South Africa",
    "operator": null,
    "designee": null,
    "protocolCategories": "Chemical industry",
    "resourceStatus": "Under development",
    "country": "South Africa",
    "estAnnualEmissionReductions": 200000,
    "region": "Africa",
    "version": "VCS Version 3",
    "protocols": "VM0016",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-04-22"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2508",
    "resourceName": "UNITOR REDD+ PROJECT",
    "proponent": "Multiple Proponents",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under development",
    "country": "Brazil",
    "estAnnualEmissionReductions": 522923,
    "region": "Latin America",
    "version": "VCS Version 3",
    "protocols": "VM0015",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-04-20"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2505",
    "resourceName": "Fuel Efficient Cooking in South Africa",
    "proponent": "TASC SA (Pty) Ltd.",
    "operator": null,
    "designee": null,
    "protocolCategories": "Energy demand",
    "resourceStatus": "Under development",
    "country": "South Africa",
    "estAnnualEmissionReductions": 2830189,
    "region": "Africa",
    "version": "VCS Version 3",
    "protocols": "AMS-II.G., VMR0006",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-04-20"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2504",
    "resourceName": "Adjusted Water Management in Rice Cultivation in Xuanzhou District",
    "proponent": "Hefei Luyu Agricultural Technology Co., Ltd",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use, Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under validation",
    "country": "China",
    "estAnnualEmissionReductions": 58064,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "AMS-III.AU",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-04-20"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2506",
    "resourceName": "Adjusted Water Management in Rice Cultivation In Northern Lujiang County",
    "proponent": "Hefei Luyu Agricultural Technology Co., Ltd",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use, Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under validation",
    "country": "China",
    "estAnnualEmissionReductions": 59282,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "AMS-III.AU",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-04-20"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2507",
    "resourceName": "Adjusted Water Management in Rice Cultivation In Southern Lujiang County",
    "proponent": "Hefei Luyu Agricultural Technology Co., Ltd",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use, Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under validation",
    "country": "China",
    "estAnnualEmissionReductions": 59043,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "AMS-III.AU",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-04-20"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2503",
    "resourceName": "Liling LFG Power Generation Project",
    "proponent": "Zhuzhou Xinzhongshui Environmental Protection Technology Co., Ltd.",
    "operator": null,
    "designee": null,
    "protocolCategories": "Waste handling and disposal",
    "resourceStatus": "Under development",
    "country": "China",
    "estAnnualEmissionReductions": 70383,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "ACM0001",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-04-19"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2501",
    "resourceName": "Durban Landfill-Gas Bisasar Road.",
    "proponent": "Converted from other GHG program",
    "operator": null,
    "designee": null,
    "protocolCategories": "Energy industries (renewable/non-renewable sources)",
    "resourceStatus": "Credits Transferred from Approved GHG Program",
    "country": "South Africa",
    "estAnnualEmissionReductions": 342705,
    "region": "Africa",
    "version": "VCS Version 3",
    "protocols": "AM0010",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-04-16"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2499",
    "resourceName": "Guangzhou Huadu Shiling LFG Power Generation Project",
    "proponent": "Guangzhou Zhongshui Recycling Environmental Protection Technology Co., Ltd.",
    "operator": null,
    "designee": null,
    "protocolCategories": "Waste handling and disposal",
    "resourceStatus": "Registration and verification approval requested",
    "country": "China",
    "estAnnualEmissionReductions": 143339,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "ACM0001",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-04-13"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2498",
    "resourceName": "AFFORESTATION OF DEGRADED GRASSLANDS IN A CAAZAPA",
    "proponent": "Miller Forest Investment AG",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under development",
    "country": "Paraguay",
    "estAnnualEmissionReductions": 955817,
    "region": "Latin America",
    "version": "VCS Version 3",
    "protocols": "ACM0003",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-04-12"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2496",
    "resourceName": "IMPACT REFORESTATION IN THE CHACO PROJECT",
    "proponent": "Investancia Paraguay S.A.",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under validation",
    "country": "Paraguay",
    "estAnnualEmissionReductions": 1000000,
    "region": "Latin America",
    "version": "VCS Version 3",
    "protocols": "ACM0003",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-04-06"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2497",
    "resourceName": "TIST Program in Uganda, VCS-CCB 011",
    "proponent": "Clean Air Action Corporation",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under validation",
    "country": "Uganda",
    "estAnnualEmissionReductions": 99748,
    "region": "Africa",
    "version": "VCS Version 3",
    "protocols": "AR-AMS0007",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-04-06"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2489",
    "resourceName": "Viet Nam Improved Cookstove Project by KCM – Improved Cookstove Project in Hoa Binh Province – CPA 002",
    "proponent": "Korea Carbon Management Ltd",
    "operator": null,
    "designee": null,
    "protocolCategories": "Energy demand",
    "resourceStatus": "Under development",
    "country": "Viet Nam",
    "estAnnualEmissionReductions": 45742,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "AMS-II.G.",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-03-31"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2490",
    "resourceName": "Viet Nam Improved Cookstove Project by KCM – Improved Cookstove Project in Phu Tho Province – CPA 003",
    "proponent": "Korea Carbon Management Ltd",
    "operator": null,
    "designee": null,
    "protocolCategories": "Energy demand",
    "resourceStatus": "Under development",
    "country": "Viet Nam",
    "estAnnualEmissionReductions": 46339,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "AMS-II.G.",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-03-31"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2486",
    "resourceName": "Hydrogen based steam generation at New Johnsonville",
    "proponent": "Multiple Proponents",
    "operator": null,
    "designee": null,
    "protocolCategories": "Energy industries (renewable/non-renewable sources)",
    "resourceStatus": "Under development",
    "country": "United States",
    "estAnnualEmissionReductions": 20108,
    "region": "North America",
    "version": "VCS Version 3",
    "protocols": "AMS-III.B.",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-03-30"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2487",
    "resourceName": "Viet Nam Improved Cookstove Project by KCM – Improved Cookstove Project in Hoa Binh Province – CPA 001",
    "proponent": "Korea Carbon Management Ltd",
    "operator": null,
    "designee": null,
    "protocolCategories": "Energy demand",
    "resourceStatus": "Under development",
    "country": "Viet Nam",
    "estAnnualEmissionReductions": 44888,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "AMS-II.G.",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-03-30"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2485",
    "resourceName": "Agri-SMART: Sustaining a resilient and inclusive development in Zambezia",
    "proponent": "Carbon Sink Group s.r.l.",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under validation",
    "country": "Mozambique",
    "estAnnualEmissionReductions": 4799,
    "region": "Africa",
    "version": "VCS Version 3",
    "protocols": "VM0017",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-03-29"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2484",
    "resourceName": "WM ENERGY BIOGAS PLANT",
    "proponent": "Multiple Proponents",
    "operator": null,
    "designee": null,
    "protocolCategories": "Livestock, enteric fermentation, and manure management, Energy industries (renewable/non-renewable sources); Livestock, enteric fermentation, and manure management; Waste handling and disposal",
    "resourceStatus": "Under development",
    "country": "Turkey",
    "estAnnualEmissionReductions": 56463,
    "region": "Middle East",
    "version": "VCS Version 3",
    "protocols": "AMS-I.D., AMS-III.D.",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-03-28"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2483",
    "resourceName": "PNG Communities BEST REDD - Tavolo Project",
    "proponent": "FORCERT Limited",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under development",
    "country": "Papua New Guinea",
    "estAnnualEmissionReductions": 202142,
    "region": "Oceania",
    "version": "VCS Version 3",
    "protocols": "VM0007",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-03-27"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2482",
    "resourceName": "Boa Fé REDD Project",
    "proponent": "Multiple Proponents",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under development",
    "country": "Brazil",
    "estAnnualEmissionReductions": 1295172,
    "region": "Latin America",
    "version": "VCS Version 3",
    "protocols": "VM0015",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-03-26"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2479",
    "resourceName": "Mahogany Plantation in India",
    "proponent": "Mahogani Vishwa Agro Pvt Ltd",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under development",
    "country": "India",
    "estAnnualEmissionReductions": 692175,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "AR-ACM0003",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-03-26"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2481",
    "resourceName": "Generation Forest Group Project",
    "proponent": "Futuro Forestal",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under validation",
    "country": "Panama",
    "estAnnualEmissionReductions": 27000,
    "region": "Latin America",
    "version": "VCS Version 3",
    "protocols": "ACM0003",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-03-26"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2478",
    "resourceName": "Reducing Gas Leakages within the Titas Gas Distribution Network in Bangladesh",
    "proponent": "Converted from other GHG program",
    "operator": null,
    "designee": null,
    "protocolCategories": "Fugitive emissions from fuels (solid, oil and gas)",
    "resourceStatus": "Credits Transferred from Approved GHG Program",
    "country": "Bangladesh",
    "estAnnualEmissionReductions": 3481722,
    "region": null,
    "version": "VCS Version 3",
    "protocols": "AM0023",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-03-25"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2476",
    "resourceName": "Huaining Adjusted Water Management in Rice Cultivation",
    "proponent": "LibraCarbon",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use, Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under validation",
    "country": "China",
    "estAnnualEmissionReductions": 58041,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "AMS-III.AU",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-03-25"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2477",
    "resourceName": "Wanfan Adjusted Water Management in Rice Cultivation",
    "proponent": "LibraCarbon",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use, Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under validation",
    "country": "China",
    "estAnnualEmissionReductions": 59986,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "AMS-III.AU",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-03-25"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2474",
    "resourceName": "Fujian Shunchang IFM (conversion of logged to protected forest) Project",
    "proponent": "Fujian Shunchang State-owned Forest Farm",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under development",
    "country": "China",
    "estAnnualEmissionReductions": 171947,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "VM0010",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-03-22"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2473",
    "resourceName": "Installation of High Efficient Cook Stoves by Enking International",
    "proponent": "EKI Energy Services Limited",
    "operator": null,
    "designee": null,
    "protocolCategories": "Energy demand, Energy demand",
    "resourceStatus": "Under development",
    "country": "India",
    "estAnnualEmissionReductions": 47082,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "VMR0006",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-03-19"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2470",
    "resourceName": "Development of Programmatic CDM Project for SWH installation under MNRE, UNDP/GEF Global Solar Water Heating Market Transformation and Strengthening Initiatives: India Country Programme – CPA 0001",
    "proponent": "G K Energy Marketers Pvt. Ltd",
    "operator": null,
    "designee": null,
    "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
    "resourceStatus": "Under development",
    "country": "India",
    "estAnnualEmissionReductions": 8832,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "AMS.I.J, AMS-I.L.",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-03-09"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2468",
    "resourceName": "Gaizhou Landfill Gas Power Generation Project",
    "proponent": "Gaizhou Xinzhongshui Environmental Protection Technology Co., Ltd.",
    "operator": null,
    "designee": null,
    "protocolCategories": "Waste handling and disposal, Energy industries (renewable/non-renewable sources)",
    "resourceStatus": "Registration requested",
    "country": "China",
    "estAnnualEmissionReductions": 134180,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "ACM0001",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-03-04"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2467",
    "resourceName": "Bayburt Landfill Gas to energy Project",
    "proponent": "BK Alternatif Enerji Anonim Sirketi",
    "operator": null,
    "designee": null,
    "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
    "resourceStatus": "Under development",
    "country": "Turkey",
    "estAnnualEmissionReductions": 21306,
    "region": "Europe",
    "version": "VCS Version 3",
    "protocols": "AMS-III.G.",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-03-03"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2466",
    "resourceName": "BUNDLED WIND POWER PROJECT IN TAMILNADU, INDIA CO-ORDINATED BY THE TAMILNADU SPINNING MILLS ASSOCIATION (TASMA.)",
    "proponent": "TAMILNADU SPINNING MILLS ASSOCIATION (TASMA)",
    "operator": null,
    "designee": null,
    "protocolCategories": "Energy industries (renewable/non-renewable sources)",
    "resourceStatus": "Registration requested",
    "country": "India",
    "estAnnualEmissionReductions": 801520,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "ACM0002",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-03-02"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2464",
    "resourceName": "Nanning Landfill Gas Power Generation Project",
    "proponent": "Guangxi Ruirong Energy Technology Co., Ltd.",
    "operator": null,
    "designee": null,
    "protocolCategories": "Waste handling and disposal, Energy industries (renewable/non-renewable sources)",
    "resourceStatus": "Registration requested",
    "country": "China",
    "estAnnualEmissionReductions": 231811,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "ACM0001",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-02-26"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2463",
    "resourceName": "Fuel Efficient Stoves in Zambia CPA 3.",
    "proponent": "Credits transferred from approved GHG program",
    "operator": null,
    "designee": null,
    "protocolCategories": "Energy demand",
    "resourceStatus": "Credits Transferred from Approved GHG Program",
    "country": "Zambia",
    "estAnnualEmissionReductions": 40864,
    "region": null,
    "version": "VCS Version 3",
    "protocols": "AMS-II.G.",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-02-22"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2461",
    "resourceName": "Convergence Energy Services Ltd. (CESL) EV Charging Infrastructure Project",
    "proponent": "Convergence Energy Services Private Limited",
    "operator": null,
    "designee": null,
    "protocolCategories": "Energy distribution",
    "resourceStatus": "Under development",
    "country": "India",
    "estAnnualEmissionReductions": 15129,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "VM0038",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-02-17"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2460",
    "resourceName": "GZL ENERGY BIOGAS PLANT",
    "proponent": "Multiple Proponents",
    "operator": null,
    "designee": null,
    "protocolCategories": "Livestock, enteric fermentation, and manure management, Energy industries (renewable/non-renewable sources); Livestock, enteric fermentation, and manure management; Waste handling and disposal",
    "resourceStatus": "Under development",
    "country": "Turkey",
    "estAnnualEmissionReductions": 52348,
    "region": "Middle East",
    "version": "VCS Version 3",
    "protocols": "AMS-I.D., AMS-III.D.",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-02-11"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2459",
    "resourceName": "NAYA REDD+",
    "proponent": "Multiple Proponents",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under development",
    "country": "Colombia",
    "estAnnualEmissionReductions": 350000,
    "region": "Latin America",
    "version": "VCS Version 3",
    "protocols": "VM0007",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-02-10"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2458",
    "resourceName": "Guoluo Grassland Sustainable Management Project",
    "proponent": "Qinghai Guanglv Landscaping Co., Ltd.",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use",
    "resourceStatus": "Registration and verification approval requested",
    "country": "China",
    "estAnnualEmissionReductions": 456953,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "VM0026",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-02-09"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2455",
    "resourceName": "Haicheng Landfill Gas Power Generation Project",
    "proponent": "Haicheng Xinzhongshui Environmental Protection Technology Co., Ltd",
    "operator": null,
    "designee": null,
    "protocolCategories": "Waste handling and disposal, Energy industries (renewable/non-renewable sources)",
    "resourceStatus": "Registration requested",
    "country": "China",
    "estAnnualEmissionReductions": 81914,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "ACM0001",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-02-08"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2457",
    "resourceName": "BYZ GLOBAL ENERGY BIOGAS PLANT",
    "proponent": "Multiple Proponents",
    "operator": null,
    "designee": null,
    "protocolCategories": "Livestock, enteric fermentation, and manure management, Energy industries (renewable/non-renewable sources); Livestock, enteric fermentation, and manure management; Waste handling and disposal",
    "resourceStatus": "Under development",
    "country": "Turkey",
    "estAnnualEmissionReductions": 50576,
    "region": "Middle East",
    "version": "VCS Version 3",
    "protocols": "AMS-I.D., AMS-III.D.",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-02-08"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2452",
    "resourceName": "Laizhou Landfill Gas Power Generation Project",
    "proponent": "Laizhou Xinzhongshui Environmental Protection Technology Co., Ltd.",
    "operator": null,
    "designee": null,
    "protocolCategories": "Waste handling and disposal, Energy industries (renewable/non-renewable sources)",
    "resourceStatus": "Registration requested",
    "country": "China",
    "estAnnualEmissionReductions": 78184,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "ACM0001",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-02-04"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2450",
    "resourceName": "Starsight Energy - Rooftop Solar PV and Efficient Air Conditioners",
    "proponent": "Starsight Power Utility Limited",
    "operator": null,
    "designee": null,
    "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy demand",
    "resourceStatus": "Registration requested",
    "country": "Nigeria",
    "estAnnualEmissionReductions": 16457,
    "region": "Africa",
    "version": "VCS Version 3",
    "protocols": "AMS-II.E.",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-02-02"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2451",
    "resourceName": "Shanxi Loufan Afforestation Project",
    "proponent": "Loufan County Forestry Workstation",
    "operator": null,
    "designee": null,
    "protocolCategories": "Agriculture Forestry and Other Land Use",
    "resourceStatus": "Under development",
    "country": "China",
    "estAnnualEmissionReductions": 164917,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "AR-ACM0003",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-02-02"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2449",
    "resourceName": "Tradewater International Dominican Republic",
    "proponent": "Tradewater International SRL",
    "operator": null,
    "designee": null,
    "protocolCategories": "Fugitive emissions from production and consumption of halocarbons and sulphur hexafluoride",
    "resourceStatus": "Registered",
    "country": "Dominican Republic",
    "estAnnualEmissionReductions": 4000,
    "region": "Latin America",
    "version": "VCS Version 3",
    "protocols": "VM0016",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-02-01"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2445",
    "resourceName": "Bundled Solar Water Heater Project",
    "proponent": "G K Energy Marketers Pvt. Ltd",
    "operator": null,
    "designee": null,
    "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
    "resourceStatus": "Under development",
    "country": "India",
    "estAnnualEmissionReductions": 22746,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "AMS-I.C.",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-01-28"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2435",
    "resourceName": "Distribution of Improved cook stove - Phase 7",
    "proponent": "G K Energy Marketers Pvt. Ltd",
    "operator": null,
    "designee": null,
    "protocolCategories": "Energy demand, Energy demand",
    "resourceStatus": "Under development",
    "country": "India",
    "estAnnualEmissionReductions": 12999,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "AMS-II.G.",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-01-28"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2436",
    "resourceName": "Distribution of Improved cook stove - Phase 8",
    "proponent": "G K Energy Marketers Pvt. Ltd",
    "operator": null,
    "designee": null,
    "protocolCategories": "Energy demand, Energy demand",
    "resourceStatus": "Under development",
    "country": "India",
    "estAnnualEmissionReductions": 12627,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "AMS-II.G.",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-01-28"
  },
  {
    "program": "Verified Carbon Standard",
    "resourceIdentifier": "2437",
    "resourceName": "Distribution of Improved cook stove - Phase 9",
    "proponent": "G K Energy Marketers Pvt. Ltd",
    "operator": null,
    "designee": null,
    "protocolCategories": "Energy demand, Energy demand",
    "resourceStatus": "Under development",
    "country": "India",
    "estAnnualEmissionReductions": 13196,
    "region": "Asia",
    "version": "VCS Version 3",
    "protocols": "AMS-II.G.",
    "compatibleProgramScenarioTypeName": null,
    "inputTypes": null,
    "createDate": "2021-01-28"
  }
]

export default projects;